development:
  adapter: mysql
  encoding: utf8
  database: sauce_development
  username: root
  host: localhost
  socket: /opt/local/var/run/mysql5/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  database: sauce_test
  username: root
  host: localhost
  socket: /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: sqlite3
  database: db/production.sqlite3
  timeout: 5000


